### ISSUE TITLE
No progress after USB device opened

### ISSUE THREAD

**Issue by christiangroth** [jckuester/weather-station#12]
Hi,

first of all thanks for sharing your project!!

As I am new to Arduino I was playing around with your app. The situation I'm ending up in is the following:

  pi@pi:~/weather-station_0.1.0_linux_armv7 $ ll /dev/ttyUSB*
  crw-rw---- 1 root dialout 188, 0 Aug 27 19:49 /dev/ttyUSB0
  
  pi@pi:~/weather-station_0.1.0_linux_armv7 $ ./weather-station --device="/dev/ttyUSB0"
  2018/08/27 20:11:53 Serving metrics at ':8080/metrics'
  2018/08/27 20:11:53 Device '/dev/ttyUSB0' opened

So there is only one USB device and thats the Arduino, but I don't get the ready message and the app is stuck. I do not get any error or timeout (waited for some minutes). There aren't also any entries in /var/log/syslog or dmesg.

I tested the Arduino using Arduino IDE and the serial monitor, sending the homeduino commands by myself and I received 433MHz signals without any problems. So I'm quite sure the arduino part is fine.

Seems like my Arduino part is missing something but as there are no more dependencies in the Readme I'm quite out of ideas right now. Maybe you can give a hint?

**Comment by martinhoefling** [comment]
You're using a Mac? I have the same problem, since you cannot set your tty device to 115200 baud via stty. Maybe using https://github.com/jacobsa/go-serial instead of just opening the device would help.

**Comment by christiangroth** [comment]
I do not understand what that has to do with a Mac problem. The program runs on the Raspberry Pi. In addition to Mac and Windows, I just tested whether the Arduino part works properly for itself, without weatherstation binary, only using the Arduno IDE. It worked on both platforms, so the Arduino works fine and the problem has to be on the Pi. I just do not know how to analyze further.

**Comment by martinhoefling** [comment]
So on a mac, it is not possible to set the baudrate of the serial device. Maybe this is also an issue on the raspi. Arduino IDE (like screen) uses system calls in C to setup the serial connection baudrate. Normally, you would do this via `stty` but this is not working on OSX. Can you connect via `screen` and setting the baudrate?

**Comment by martinhoefling** [comment]
After setting the tty to 115200 baud on a linux machine, it works somewhat:
```
~# stty -F /dev/ttyUSB0
speed 9600 baud; line = 0;
-brkint -imaxbel
~# stty -F /dev/ttyUSB0 115200
~# stty -F /dev/ttyUSB0
speed 115200 baud; line = 0;
-brkint -imaxbel
```

```
~# ./weather-station --device="/dev/ttyUSB0"
2018/09/01 17:21:45 Serving metrics at ':8080/metrics'
2018/09/01 17:21:45 Device '/dev/ttyUSB0' opened
2018/09/01 17:21:45 ready
2018/09/01 17:21:45 Wrote command 'RF receive 0' to '/dev/ttyUSB0' (13 bytes)
2018/09/01 17:21:45
2018/09/01 17:21:46 ready
2018/09/01 17:21:46
2018/09/01 17:21:46 ERR unknown_command
```

Any ideas?

**Comment by christiangroth** [comment]
Yeah, great!! That did the trick! Now I'm able to connect to Arduino from Pi. Unfortunately I get the same errors regarding unknown command:

    pi@pi:~/weather-station_0.1.0_linux_armv7 $ ./weather-station --device="/dev/ttyUSB0" 
    2018/09/01 18:12:36 Serving metrics at ':8080/metrics'
    2018/09/01 18:12:36 Device '/dev/ttyUSB0' opened
    2018/09/01 18:12:36 ERR unknown_command
    2018/09/01 18:12:36 
    2018/09/01 18:12:36 ready
    2018/09/01 18:12:36 Wrote command 'RF receive 0' to '/dev/ttyUSB0' (13 bytes)
    2018/09/01 18:12:36 
    2018/09/01 18:12:38 ready
    2018/09/01 18:12:38 
    2018/09/01 18:12:38 ERR unknown_command
    2018/09/01 18:12:38 
    2018/09/01 18:12:38 ERR unknown_command
    2018/09/01 18:12:38 
    2018/09/01 18:12:38 ERR unknown_command
    2018/09/01 18:12:38 
    2018/09/01 18:12:38 ERR unknown_command
    2018/09/01 18:12:38

**Comment by jckuester** [comment]
Hey guys, sorry for being late to this issue - I've been hiking for some days :)

There have been some changes in the main branch by @panzerdev, which didn't end up in the first release. These changes reset the Arduino into some expected state. I made a new [v0.2](https://github.com/jckuester/weather-station/releases/tag/v0.2.0) release. 

Can you please check if that helps?

**Comment by martinhoefling** [comment]
I get a slightly different error with v0.2.0

```
~# ./weather-station --device="/dev/ttyUSB0"
2018/09/02 00:07:12 Device '/dev/ttyUSB0' opened
2018/09/02 00:07:12 Wrote command 'RESET' to '/dev/ttyUSB0' (6 bytes)
2018/09/02 00:07:12 Line Scanned: ERR unknown_command
2018/09/02 00:07:12 Not ready msg: ERR unknown_command
2018/09/02 00:07:12 Line Scanned:
2018/09/02 00:07:12 Not ready msg:
2018/09/02 00:07:14 Line Scanned: ready
2018/09/02 00:07:14 Serving metrics at ':8080/metrics'
2018/09/02 00:07:14 Wrote command 'RF receive 0' to '/dev/ttyUSB0' (13 bytes)
2018/09/02 00:07:14 Write RF receive 0
2018/09/02 00:07:14 Line Scanned:
2018/09/02 00:07:14 Line Scanned: ERR unknown_command
2018/09/02 00:07:14 Line Scanned:
2018/09/02 00:07:14 Line Scanned: ACK
2018/09/02 00:07:14 Line Scanned:
2018/09/02 00:07:14 Line Scanned: ERR unknown_command
2018/09/02 00:07:14 Line Scanned:
2018/09/02 00:07:14 Line Scanned: ERR unknown_command
```

**Comment by martinhoefling** [comment]
OK, resetting via screen solved the issue for me. Just the temperature is strange now:

```
2018/09/02 00:40:38 Line Scanned: RF receive 580 4028 1996 8924 0 0 0 0 0101020101010102020201020202020201010202010101010102020202010202020201020203
2018/09/02 00:40:38 GT_WT_01: {ID:3554 Name:3554 Channel:1 Temperature:332 Humidity:66 LowBattery:false}
2018/09/02 00:40:39 Line Scanned: RF receive 576 4040 1996 8936 0 0 0 0 0101020101010102020201020202020201010202010101010102020202010202020201020203
2018/09/02 00:40:39 GT_WT_01: {ID:3554 Name:3554 Channel:1 Temperature:332 Humidity:66 LowBattery:false}
```

**Comment by jckuester** [comment]
Great. What do you mean by resetting via screen?

Which sensors are you using, the exact same GT_WT_01 models I have? I am
asking as there are two models which use different encodings.

**Comment by christiangroth** [comment]
Using v0.2.0 I'm getting the same errors as @martinhoefling with this version (before the reset). It would be great if you could provide the command / commands used to reset via screen. Unfortunately I cant get a connection using screen, but it very likely I'm doing something wrong.

**Comment by martinhoefling** [comment]
As far as I can remember, I just did connect via `screen /dev/ttyUSB0 115200` and did a disconnect via CTRL+A K. 

The sensor works with the non variant params as described in #13. The sensor is from [Techvance](https://www.amazon.de/gp/product/B06XSWFKF4/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1).

**Comment by christiangroth** [comment]
So I again played around a bit and I'm in the same situation as @martinhoefling now. I could manage to connect to arduino via screen, but disconnecting using ctrl+a or any other command did not work. However in the end I just killed the screen process from another terminal. After that I started the weather station binary and got the same unknown command error slike before. But simply starting it again worked and it's receiving values.

Now it seems I can just start it, stop it and repeat this over and over and everything works. Not sure what excatly was the problem getting it to work.

I also get strange values for temperature and humidity (at least seems to be kind of in the same range, but its off by some values):

    pi@pi:~/weather-station_0.2.0_linux_armv7 $ ./weather-station 1888=entrance
    2018/09/03 21:34:57 Device '/dev/ttyUSB0' opened
    2018/09/03 21:34:57 Wrote command 'RESET' to '/dev/ttyUSB0' (6 bytes)
    2018/09/03 21:34:57 Line Scanned: ready
    2018/09/03 21:34:57 Serving metrics at ':8080/metrics'
    2018/09/03 21:34:57 Wrote command 'RF receive 0' to '/dev/ttyUSB0' (13 bytes)
    2018/09/03 21:34:57 Write RF receive 0
    2018/09/03 21:34:57 Line Scanned: ACK
    2018/09/03 21:35:10 Line Scanned: RF receive 468 692 216 264 61244 0 0 0 0111111100000000000000000012000000121212300030303030303012123012303031121231121231311224
    2018/09/03 21:35:10 Device Unknown
    2018/09/03 21:35:11 Line Scanned: RF receive 340 640 228 61232 0 0 0 0 0111111100000000010000010112010101121212010101010101010112120112010121121221121221011223
    2018/09/03 21:35:11 Device Unknown
    2018/09/03 21:35:17 Line Scanned: RF receive 604 2032 4084 8988 0 0 0 0 0102020201020201010101010101010102020201020202020102020101010202020101020103
    2018/09/03 21:35:17 GT_WT_01: {ID:1888 Name:1888 Channel:1 Temperature:383 Humidity:57 LowBattery:false}
    2018/09/03 21:35:18 Line Scanned: RF receive 600 2032 4080 8992 0 0 0 0 0102020201020201010101010101010102020201020202020102020101010202020101020103
    2018/09/03 21:35:18 GT_WT_01: {ID:1888 Name:1888 Channel:1 Temperature:383 Humidity:57 LowBattery:false}
    2018/09/03 21:35:41 Line Scanned: RF receive 476 704 220 272 61236 0 0 0 0111111100000000000000000012000000121212300030303030303012123012303030121230121230211224
    2018/09/03 21:35:41 Device Unknown
    2018/09/03 21:35:42 Line Scanned: RF receive 308 636 212 61224 0 0 0 0 0111111100010000010101010112010101121212010101010101010112120112010101121201121201011203
    2018/09/03 21:35:42 Device Unknown
    2018/09/03 21:36:07 Line Scanned: RF receive 604 2028 4084 8996 0 0 0 0 0102020201020201010101010101010102020201020202020102020101010202020101020103
    2018/09/03 21:36:07 GT_WT_01: {ID:1888 Name:1888 Channel:1 Temperature:383 Humidity:57 LowBattery:false}
    2018/09/03 21:36:08 Line Scanned: RF receive 604 2028 4076 8972 0 0 0 0 0102020201020201010101010101010102020201020202020102020101010202020101020103
    2018/09/03 21:36:08 GT_WT_01: {ID:1888 Name:1888 Channel:1 Temperature:383 Humidity:57 LowBattery:false}
    2018/09/03 21:36:12 Line Scanned: RF receive 432 664 232 268 61244 0 0 0 0111111100000000000000000012000000121212300000313131313112123112312121121221121221211224
    2018/09/03 21:36:12 Device Unknown
    2018/09/03 21:36:13 Line Scanned: RF receive 448 716 212 268 61224 0 0 0 0111111100000000000000000012000000121212003000003000000012123012003000121230121230301234
    2018/09/03 21:36:13 Device Unknown
    2018/09/03 21:36:43 Line Scanned: RF receive 412 676 212 256 61236 0 0 0 0111111100000000000000000012000000121212000000000000000112120112010131121231121231311234
    2018/09/03 21:36:43 Device Unknown
    2018/09/03 21:36:44 Line Scanned: RF receive 316 636 212 61224 0 0 0 0 0111111100000000010101010112010101121212010101010101010112120112010101121201121201011203
    2018/09/03 21:36:44 Device Unknown

I also get a lot of unkown device messages, most likley it's stuff from my neighbours I think??

@martinhoefling Seems we have bought the same sensor. Would be great to have this pull request!

**Comment by christiangroth** [comment]
Maybe another hint: When disconnecting the Arduino and reconnecting USB cable I have to
* connect via screen
* kill the screen process
* start weather station binary (getting ERR unknown command)
* start weather station binary again

This is can be reproduced.

**Comment by martinhoefling** [comment]
@christiangroth , you also have a 'non variant' sensor, see #13. I am waiting for a response if my suggestion is an acceptable solution and can provide a pull request then. You can also just edit the protocol and adjust the values to weather12.coffee

**Comment by panzerdev** [comment]
Hi to all.... I had the same problems often and decided to reduce the homeduino software to make it only receive all the time, basically only use RFControl. At least that is the only thing I am doing with mine right now.

**Comment by christiangroth** [comment]
Hi @panzerdev , what exactly do you mean by "reduce the homeduino software"? Did you change the binary flashes to arduino? In case this project does onle use the RESET and RF receive commands as fas as I can see.

**Comment by panzerdev** [comment]
@christiangroth basically yes. I reduced the Arduino firmware until I was just left with always receiving and writing to serial. 
https://github.com/panzerdev/433mhz-receiver/blob/master/arduino/homeduino.ino
It's not really homeduino anymore.
I also changed the go receiver to be multiple purpose because I have more 433 transmitter and the one is from the doorbell for example.

**Comment by christiangroth** [comment]
@panzerdev ah okay I see, thanks for sharing. Can be a solution, but I think I'll first with the fix and PR by @martinhoefling. So I'll close this issue now as there are no open problems left.
