### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by ssnjrthegr8** [jckuester/weather-station#8]
Hi, can I contribute to this project by designing a logo for it?

**Comment by jckuester** [comment]
Sure, why not! Always appreciated :)

**Comment by ssnjrthegr8** [comment]
Here it is. Hope you like it! I can send you the files if you are going to use my files
![g5834](https://user-images.githubusercontent.com/38104354/39416534-4cf50e0e-4c6b-11e8-8f8b-93540b9e7044.png)
![g5826](https://user-images.githubusercontent.com/38104354/39416535-4d358eca-4c6b-11e8-981b-733298f1d643.png)
![g6050](https://user-images.githubusercontent.com/38104354/39416533-4cad3d4a-4c6b-11e8-83b0-9c2e094a1787.png)
![g5752](https://user-images.githubusercontent.com/38104354/39416532-4c6692fa-4c6b-11e8-99ed-6c0533504d20.png)

**Comment by jckuester** [comment]
Subtle is probably ok. The reason why I am saying this, is that the main README page has a lot of colors already (pictures and badges), so not to overload it with bright colors would be good.

**Comment by ssnjrthegr8** [comment]
I apologise for the delay, I have finalised the design and I think the monochrome versions of the logo looks the best. Here are the files : https://drive.google.com/open?id=1o8o4leZewpvSFWvw9lp6OMVTcboGnDgK  If you want any changes or something feel free to contact me. It's been a pleasure contributing to this project. Thank you.
![banner_4k_blk](https://user-images.githubusercontent.com/38104354/39639876-2448505e-4fe7-11e8-9fa3-c676e1ecf38d.png)
![banner_4k_wht](https://user-images.githubusercontent.com/38104354/39639884-24eb1e24-4fe7-11e8-8585-1eec09252570.png)
![banner_4k_color](https://user-images.githubusercontent.com/38104354/39639880-249adda6-4fe7-11e8-859c-e30ca4a0d944.png)

**Comment by jckuester** [comment]
Looks great!

**Comment by ssnjrthegr8** [comment]
So, are you gonna use it :) ?

**Comment by jckuester** [comment]
I created a PR. If you are ok with it, I merge it.
